apiVersion: v1
kind: Service
metadata:
  name: agent-factory
  namespace: {{ .Values.namespace }}
  labels:
    app: agent-factory
spec:
  {{- if .Values.service.enableDualStack }}
  ipFamilies:
    - IPv6
    - IPv4
  ipFamilyPolicy: PreferDualStack
  {{- end }}
  ports:
    - name: public-port
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.port }}
      {{- end}}
  selector:
    app: agent-factory
  type: {{ .Values.service.type }}
